### PR TITLE
changed images and modified aam gallery

### PR DESCRIPTION
**Pull request by Harshit2575**

### CODE REVIEW

**Comment by punit121** [comment]
@Harshit2575 first pull from git (changes made by yugam  ) then send pull request

**Comment by Harshit2575** [comment]
Pulled those changes and changed gallery, replaced associations with sponsors, added images

**Comment by Harshit2575** [comment]
Added icons to all pages, improved gallery, changed images, replaced associations with sponsors.

**Comment by punit121** [comment]
Good Work @Harshit2575  (y)

**Pull request merged**
